イベント会場を「株式会社インプレス」に更新
ichiyasa-g-2/ichiyasaGitSample pull request #8
Opened 2021-12-27 03:26 UTC by ichiyasa-g-2

### 変更内容
イベント開催会場を「株式会社インプレス」に更新しました。
### 背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2022-01-13 07:22 UTC, shiga-iyg-2 commented on index.html
> +                                <p>大阪を中心に仕事している、ふつうのプログラマで。</p>
「す」を追加してください。

2022-01-13 07:25 UTC, shiga-iyg-2 requested changes
修正ありがとうございます。指摘の確認と修正をお願いします

2022-01-13 07:25 UTC, shiga-iyg-2 commented on index.html
> +                                <p>大阪を中心に仕事している、ふつうのプログラマで。</p>
「す」が抜けているので追加してください。

2022-01-13 07:30 UTC, ichiyasa-g-2 commented on index.html
> +                                <p>大阪を中心に仕事している、ふつうのプログラマで。</p>
修正したものをプッシュしたので、再度確認お願いします。

2022-01-13 07:31 UTC, shiga-iyg-2 commented on index.html
> +                                <p>大阪を中心に仕事している、ふつうのプログラマで。</p>
ありがとうございます 🙌

2022-01-13 07:40 UTC, shiga-iyg-2 approved these changes

2022-01-14 01:01 UTC, merged

2022-01-17 02:53 UTC, shiga-iyg-2 commented
test

2022-01-17 03:01 UTC, shiga-iyg-2 commented
![image](https://user-images.githubusercontent.com/96403614/149701633-657bfb3f-2e8f-4082-9eb3-d90371cad62a.png)